### PR TITLE
Adds Cloud Logging Service Endpoint option to configuration

### PR DESCRIPTION
**Pull request by StefanKurek**
Creates a new optional service endpoint field in the configuration page for use with regional Cloud Logging buckets. [](https://cloud.google.com/vpc/docs/regional-service-endpoints#cloud-logging)

Fixes error being displayed when can't retrieve projects. Instead just logs a warning level message.

Fixes the hide button not working on the Cloud Logging queries.

# Config Page

### Endpoint Set
image

### Endpoint Blank
image

## Bad Test Connection
image

### CODE REVIEW

**Comment by xiangshen-dk** [comment]
Can we remove the warning `Alerting not supported`? Maybe either by modifying the screenshots directly or element removal via browser inspection.

**Comment by StefanKurek** [comment]
> Can we remove the warning `Alerting not supported`? Maybe either by modifying the screenshots directly or element removal via browser inspection.

@xiangshen-dk Hello. I was only posting those screenshots for review purposes. If any of them belong inside the repo, let me know and I can try to do what you're asking.

**Comment by xiangshen-dk** [comment]
@StefanKurek Hi, we probably don't need all the screenshots in the PR since they are pretty similar. Maybe we can keep the second one (the blank endpoint). And in the doc, we can mention alternatively endpoints can be set. 

Also, can you please create a screenshot for the Query editor to show how it looks like after the configuration is done. So we can link the screenshot in README. Thanks!

**Comment by StefanKurek** [comment]
@xiangshen-dk 
1. I do currently mention in the readme about the alternate service endpoint configuration.
2. I have a screenshot linked in the plugin.json of a panel with this datasource configured, but I'll add another of the "Explorer" view and link it both in the plugin.json as well as the readme.
3. I will add an additional screenshot (config with blank endpoint) and link it both in the plugin.json as well as in the readme.

Let me know if there's anything else you'd like. Thanks!

**Comment by xiangshen-dk** [comment]
Sounds good! Thanks!

**Comment by StefanKurek** [comment]
@xiangshen-dk Just pushed the image changes. Let me know what you think. Thanks!

**Pull request merged**
